[package]
name = "rust-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = { package = "aes", version = "0.8.2" }
cha = { package = "chacha20", version = "0.9" }
aes-gcm = "0.10.2"
chacha20poly1305 = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.4"
aead = "0.5.2"
futures = "0.3.28"
sha2 = "0.10.6"
stunclient = { version = "0.4.0", default-features = false }
