[appenders.stdout]
kind = "console"
encoder = { pattern = "[{({l}):1.1}] {m}{n}" }
filters = [{ kind = "threshold", level = "info" }]

[appenders.common]
kind = "file"
path = "log/bench.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} {({l}):>5.5} - {m}{n}" }

[appenders.driver]
kind = "file"
path = "log/driver.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} {({l}):>5.5} - {m}{n}" }

[appenders.cipher]
kind = "file"
path = "log/cipher.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} {({l}):>5.5} - {m}{n}" }

[appenders.stream]
kind = "file"
path = "log/stream.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} {({l}):>5.5} - {m}{n}" }

[root]
level = "off"

[loggers]
"ensd" = { level = "trace", appenders = ["stdout", "common"], additive = false }
"ensd::stream::udp" = { level = "trace", appenders = ["stdout", "stream"], additive = false }
"ensd::stream" = { level = "trace", appenders = ["stream"], additive = false }
"ensd::cipher::aes" = { level = "trace", appenders = ["cipher"], additive = false }
"ensd::cipher::cha" = { level = "trace", appenders = ["cipher"], additive = false }
"async_io" = { level = "debug", appenders = ["driver"], additive = false }
