[appenders.stdout]
kind = "console"
encoder = { pattern = "[{h({l}):1.1}] {m}{n}" }
filters = [{ kind = "threshold", level = "info" }]

[appenders.common]
kind = "file"
path = "log/bench.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):>5.5} | T:{i:<5.5} - {m}{n}" }

[appenders.driver]
kind = "file"
path = "log/driver.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):>5.5} | T:{i:<5.5} - {m}{n}" }

[appenders.cipher]
kind = "file"
path = "log/cipher.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):>5.5} | T:{i:<5.5} - {m}{n}" }

[appenders.socket]
kind = "file"
path = "log/socket.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):>5.5} | T:{i:<5.5} - {m}{n}" }

[appenders.stream]
kind = "file"
path = "log/stream.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):>5.5} | T:{i:<5.5} - {m}{n}" }

[appenders.wasapi]
kind = "file"
path = "log/wasapi.log"
encoder = { pattern = "{d(%Y-%m-%d %H:%M:%S)} | {h({l}):>5.5} | T:{i:<5.5} - {m}{n}" }

[root]
level = "off"

[loggers]
"ensd" = { level = "trace", appenders = ["stdout", "common"], additive = false }
"socket::udp" = { level = "trace", appenders = ["stdout", "socket"], additive = false }
"socket" = { level = "trace", appenders = ["socket"] }
"cipher" = { level = "trace", appenders = ["cipher"] }
"stream" = { level = "trace", appenders = ["stream"] }
"async_io" = { level = "debug", appenders = ["driver"], additive = false }
"wasapi" = { level = "debug", appenders = ["wasapi"] }
