name: ci
on: [ workflow_call ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: apt-get install
        run: sudo apt-get install -y ${{ vars.APT_DEPS }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features ci

  check:
    uses: ./.github/workflows/check.yml
