name: test
on:
  workflow_call:
    inputs:
      coverage:
        required: false
        type: boolean
  workflow_dispatch:
    inputs:
      coverage:
        required: false
        description: generate coverage report
        type: boolean

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --features ci
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --features ci --manifest-path=crates/Cargo.toml

  cov-report:
    continue-on-error: true
    runs-on: windows-latest
    if: ${{ inputs.coverage }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-C instrument-coverage"
        with:
          command: test
          args: --workspace --features ci
